DROP TABLE IF EXISTS Asiakas CASCADE;
DROP TABLE IF EXISTS Kiinteisto CASCADE;
DROP TABLE IF EXISTS Autopaikka CASCADE;
DROP TABLE IF EXISTS Varaus;
DROP TABLE IF EXISTS Ap_alue CASCADE;
DROP TABLE IF EXISTS Jonoentry;
DROP TABLE IF EXISTS Linkitys;
DROP TABLE IF EXISTS Kayttaja;

